program ListagemFornecedor;

uses
  Vcl.Forms,
  untFormularioPrincipal in 'untFormularioPrincipal.pas' {formularioPrincipal},
  untFormularioCadastroEmpresa in 'untFormularioCadastroEmpresa.pas' {formularioCadastroEmpresa},
  untFormularioCadastroFornecedor in 'untFormularioCadastroFornecedor.pas' {formularioCadastroFornecedor},
  untFormularioImpressao in 'untFormularioImpressao.pas' {formularioImpressao},
  untFormularioListagemEmpresas in 'untFormularioListagemEmpresas.pas' {formularioListagemEmpresas},
  untFormularioListagemFornecedores in 'untFormularioListagemFornecedores.pas' {formularioListagemFornecedores},
  RxAniFile in 'D:\Downloads\Delphi Componentes\units\RxAniFile.pas',
  RxAnimate in 'D:\Downloads\Delphi Componentes\units\RxAnimate.pas',
  RxAppEvent in 'D:\Downloads\Delphi Componentes\units\RxAppEvent.pas',
  RxAppUtils in 'D:\Downloads\Delphi Componentes\units\RxAppUtils.pas',
  RxBoxProcs in 'D:\Downloads\Delphi Componentes\units\RxBoxProcs.pas',
  RxCalc in 'D:\Downloads\Delphi Componentes\units\RxCalc.pas',
  RxCalcEditDlg in 'D:\Downloads\Delphi Componentes\units\RxCalcEditDlg.pas' {FormRxCalcEdit},
  RxClipIcon in 'D:\Downloads\Delphi Componentes\units\RxClipIcon.pas',
  RxClipMon in 'D:\Downloads\Delphi Componentes\units\RxClipMon.pas',
  RxClipView in 'D:\Downloads\Delphi Componentes\units\RxClipView.pas',
  RxClock in 'D:\Downloads\Delphi Componentes\units\RxClock.pas',
  RxColors in 'D:\Downloads\Delphi Componentes\units\RxColors.pas',
  RxCombos in 'D:\Downloads\Delphi Componentes\units\RxCombos.pas',
  RxConst in 'D:\Downloads\Delphi Componentes\units\RxConst.pas',
  RxCtrls in 'D:\Downloads\Delphi Componentes\units\RxCtrls.pas',
  RxCurrEdit in 'D:\Downloads\Delphi Componentes\units\RxCurrEdit.pas',
  RxDataConv in 'D:\Downloads\Delphi Componentes\units\RxDataConv.pas',
  RxDateUtil in 'D:\Downloads\Delphi Componentes\units\RxDateUtil.pas',
  RxDice in 'D:\Downloads\Delphi Componentes\units\RxDice.pas',
  RxDirFrm in 'D:\Downloads\Delphi Componentes\units\RxDirFrm.pas' {DirectoryListDialog},
  RxDualList in 'D:\Downloads\Delphi Componentes\units\RxDualList.pas',
  RxExcptDlg in 'D:\Downloads\Delphi Componentes\units\RxExcptDlg.pas' {RxErrorDialog},
  RxExtenders in 'D:\Downloads\Delphi Componentes\units\RxExtenders.pas',
  RxFDualLst in 'D:\Downloads\Delphi Componentes\units\RxFDualLst.pas' {DualListForm},
  RxFileUtil in 'D:\Downloads\Delphi Componentes\units\RxFileUtil.pas',
  RxGIF in 'D:\Downloads\Delphi Componentes\units\RxGIF.pas',
  RxGIFCtrl in 'D:\Downloads\Delphi Componentes\units\RxGIFCtrl.pas',
  RxGraph in 'D:\Downloads\Delphi Componentes\units\RxGraph.pas',
  RxGrdCpt in 'D:\Downloads\Delphi Componentes\units\RxGrdCpt.pas',
  RxGrids in 'D:\Downloads\Delphi Componentes\units\RxGrids.pas',
  RxHints in 'D:\Downloads\Delphi Componentes\units\RxHints.pas',
  RxHook in 'D:\Downloads\Delphi Componentes\units\RxHook.pas',
  RxIcoList in 'D:\Downloads\Delphi Componentes\units\RxIcoList.pas',
  RxImagPrvw in 'D:\Downloads\Delphi Componentes\units\RxImagPrvw.pas' {ImageForm},
  RxIni in 'D:\Downloads\Delphi Componentes\units\RxIni.pas',
  RxLogin in 'D:\Downloads\Delphi Componentes\units\RxLogin.pas' {RxLoginForm},
  RxLookup in 'D:\Downloads\Delphi Componentes\units\RxLookup.pas',
  RxMailBox in 'D:\Downloads\Delphi Componentes\units\RxMailBox.pas',
  RxMaxMin in 'D:\Downloads\Delphi Componentes\units\RxMaxMin.pas',
  RxMemDS in 'D:\Downloads\Delphi Componentes\units\RxMemDS.pas',
  RxMemDSUtil in 'D:\Downloads\Delphi Componentes\units\RxMemDSUtil.pas',
  RxMenus in 'D:\Downloads\Delphi Componentes\units\RxMenus.pas',
  RxMrgMngr in 'D:\Downloads\Delphi Componentes\units\RxMrgMngr.pas',
  RxMRUList in 'D:\Downloads\Delphi Componentes\units\RxMRUList.pas',
  RxNotify in 'D:\Downloads\Delphi Componentes\units\RxNotify.pas',
  RxNTSecurity in 'D:\Downloads\Delphi Componentes\units\RxNTSecurity.pas',
  RxObjStr in 'D:\Downloads\Delphi Componentes\units\RxObjStr.pas',
  RxOle2Auto in 'D:\Downloads\Delphi Componentes\units\RxOle2Auto.pas',
  RxPageMngr in 'D:\Downloads\Delphi Componentes\units\RxPageMngr.pas',
  RxParsing in 'D:\Downloads\Delphi Componentes\units\RxParsing.pas',
  RxPicClip in 'D:\Downloads\Delphi Componentes\units\RxPicClip.pas',
  RxPickDate in 'D:\Downloads\Delphi Componentes\units\RxPickDate.pas',
  RxPlacemnt in 'D:\Downloads\Delphi Componentes\units\RxPlacemnt.pas',
  RxPlugin in 'D:\Downloads\Delphi Componentes\units\RxPlugin.pas',
  RxPluginManager in 'D:\Downloads\Delphi Componentes\units\RxPluginManager.pas',
  RxPluginParamsForm in 'D:\Downloads\Delphi Componentes\units\RxPluginParamsForm.pas' {frmPluginParams},
  RxPrgrss in 'D:\Downloads\Delphi Componentes\units\RxPrgrss.pas',
  RxProps in 'D:\Downloads\Delphi Componentes\units\RxProps.pas',
  RxRecordGrid in 'D:\Downloads\Delphi Componentes\units\RxRecordGrid.pas',
  RxRemLog in 'D:\Downloads\Delphi Componentes\units\RxRemLog.pas',
  RxResConst in 'D:\Downloads\Delphi Componentes\units\RxResConst.pas',
  RxResConst_bul in 'D:\Downloads\Delphi Componentes\units\RxResConst_bul.pas',
  RxResConst_chi in 'D:\Downloads\Delphi Componentes\units\RxResConst_chi.pas',
  RxResConst_cht in 'D:\Downloads\Delphi Componentes\units\RxResConst_cht.pas',
  RxResConst_cze in 'D:\Downloads\Delphi Componentes\units\RxResConst_cze.pas',
  RxResConst_dan in 'D:\Downloads\Delphi Componentes\units\RxResConst_dan.pas',
  RxResConst_dut in 'D:\Downloads\Delphi Componentes\units\RxResConst_dut.pas',
  RxResConst_eng in 'D:\Downloads\Delphi Componentes\units\RxResConst_eng.pas',
  RxResConst_fra in 'D:\Downloads\Delphi Componentes\units\RxResConst_fra.pas',
  RxResConst_gal in 'D:\Downloads\Delphi Componentes\units\RxResConst_gal.pas',
  RxResConst_ger in 'D:\Downloads\Delphi Componentes\units\RxResConst_ger.pas',
  RxResConst_gre in 'D:\Downloads\Delphi Componentes\units\RxResConst_gre.pas',
  RxResConst_hun in 'D:\Downloads\Delphi Componentes\units\RxResConst_hun.pas',
  RxResConst_ita in 'D:\Downloads\Delphi Componentes\units\RxResConst_ita.pas',
  RxResConst_kor in 'D:\Downloads\Delphi Componentes\units\RxResConst_kor.pas',
  RxResConst_mex in 'D:\Downloads\Delphi Componentes\units\RxResConst_mex.pas',
  RxResConst_pol in 'D:\Downloads\Delphi Componentes\units\RxResConst_pol.pas',
  RxResConst_por in 'D:\Downloads\Delphi Componentes\units\RxResConst_por.pas',
  RxResConst_rom in 'D:\Downloads\Delphi Componentes\units\RxResConst_rom.pas',
  RxResConst_rus in 'D:\Downloads\Delphi Componentes\units\RxResConst_rus.pas',
  RxResConst_slo in 'D:\Downloads\Delphi Componentes\units\RxResConst_slo.pas',
  RxResConst_spa in 'D:\Downloads\Delphi Componentes\units\RxResConst_spa.pas',
  RxResConst_srb in 'D:\Downloads\Delphi Componentes\units\RxResConst_srb.pas',
  RxResConst_svk in 'D:\Downloads\Delphi Componentes\units\RxResConst_svk.pas',
  RxResConst_swe in 'D:\Downloads\Delphi Componentes\units\RxResConst_swe.pas',
  RxResConst_tur in 'D:\Downloads\Delphi Componentes\units\RxResConst_tur.pas',
  RxResConst_ukr in 'D:\Downloads\Delphi Componentes\units\RxResConst_ukr.pas',
  RxRichEd in 'D:\Downloads\Delphi Componentes\units\RxRichEd.pas',
  RxRichPopup in 'D:\Downloads\Delphi Componentes\units\RxRichPopup.pas',
  RxSbSetup in 'D:\Downloads\Delphi Componentes\units\RxSbSetup.pas' {SpeedbarSetupWindow},
  RxSelDSFrm in 'D:\Downloads\Delphi Componentes\units\RxSelDSFrm.pas',
  RxShell in 'D:\Downloads\Delphi Componentes\units\RxShell.pas',
  RxSlider in 'D:\Downloads\Delphi Componentes\units\RxSlider.pas',
  RxSpeedbar in 'D:\Downloads\Delphi Componentes\units\RxSpeedbar.pas',
  RxSpin in 'D:\Downloads\Delphi Componentes\units\RxSpin.pas',
  RxSplit in 'D:\Downloads\Delphi Componentes\units\RxSplit.pas',
  RxSplshWnd in 'D:\Downloads\Delphi Componentes\units\RxSplshWnd.pas',
  RxStr16 in 'D:\Downloads\Delphi Componentes\units\RxStr16.pas',
  RxStrHlder in 'D:\Downloads\Delphi Componentes\units\RxStrHlder.pas',
  RxStrUtils in 'D:\Downloads\Delphi Componentes\units\RxStrUtils.pas',
  RxSwitch in 'D:\Downloads\Delphi Componentes\units\RxSwitch.pas',
  RxTimer in 'D:\Downloads\Delphi Componentes\units\RxTimer.pas',
  RxTimerLst in 'D:\Downloads\Delphi Componentes\units\RxTimerLst.pas',
  RxToolEdit in 'D:\Downloads\Delphi Componentes\units\RxToolEdit.pas',
  RxTranslate in 'D:\Downloads\Delphi Componentes\units\RxTranslate.pas',
  RxVCLUtils in 'D:\Downloads\Delphi Componentes\units\RxVCLUtils.pas',
  RxVerInf in 'D:\Downloads\Delphi Componentes\units\RxVerInf.pas',
  RxViewer in 'D:\Downloads\Delphi Componentes\units\RxViewer.pas',
  RxDBComb in 'D:\Downloads\Delphi Componentes\units\RxDBComb.pas',
  RxDBCtrl in 'D:\Downloads\Delphi Componentes\units\RxDBCtrl.pas',
  RxDBCurrEdit in 'D:\Downloads\Delphi Componentes\units\RxDBCurrEdit.pas',
  RxDBRichEd in 'D:\Downloads\Delphi Componentes\units\RxDBRichEd.pas',
  RxDBUtils in 'D:\Downloads\Delphi Componentes\units\RxDBUtils.pas',
  untFormularioBuscaEmpresa in 'untFormularioBuscaEmpresa.pas' {formularioBuscaEmpresa},
  untFormularioImpressaoFR in 'untFormularioImpressaoFR.pas' {formularioImpressaoFR},
  untFormularioTelefones in 'untFormularioTelefones.pas' {formularioTelefones};

{$R *.res}

begin
  Application.Initialize;
  Application.MainFormOnTaskbar := True;
  Application.CreateForm(TformularioPrincipal, formularioPrincipal);
  Application.CreateForm(TformularioBuscaEmpresa, formularioBuscaEmpresa);
  Application.CreateForm(TformularioImpressaoFR, formularioImpressaoFR);
  Application.CreateForm(TformularioTelefones, formularioTelefones);
  Application.Run;
end.
